theme: jekyll-theme-minimal
title: AI4Copernicus tools and methods for bridging AI and EO
description: >
  Half-day tutorial at BiDS 2023.
  <br><br>
  <a href="https://twitter.com/AI4Copernicus"><img alt="X (formerly Twitter) Follow" src="https://img.shields.io/twitter/follow/AI4Copernicus"></a>

logo: https://ai4copernicus-project.eu/wp-content/uploads/2021/06/AI4Copernicus_-logo-transparent.png
show_downloads: false
